version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3232"

  jenkins:
#    image: jenkins/jenkins
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - .:/home
    links:
      - hub:hub.com
      - juice-shop:juice-shop

    # uncomment for docker in docker
    privileged: true